spring:
  application:
    name: stub-runner
  profiles:
    active: dev,local
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} #http://localhost:8761/eureka #eureka endpoint
    instance:
      preferIpAddress: true
      hostname: localhost
    healthcheck:
      enabled: true
    lease:
      duration: 5   